# Generated by Django 4.2.7 on 2023-11-23 22:04

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="imagem",
            field=stdimage.models.StdImageField(
                default="C:/projetos-django/fusion/media/padrao.jpg",
                force_min_size=False,
                upload_to=core.models.get_file_path,
                variations={"thumb": {"crop": True, "height": 480, "width": 480}},
                verbose_name="Imagem",
            ),
        ),
    ]
